version: '3.8'
services:
  book-store-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__BookStoreDB=Server=db;Database=BookStoreDB;User Id=sa;Password=Passw0rd;TrustServerCertificate=True;;

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: book-store-db
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
